name: MicroGames
version: 1.0-SNAPSHOT
main: net.developertobi.game.bukkit.MicroGamesPlugin
api-version: "1.21"
depend:
  - McLib

commands:
  arena:
    description: Arena commands (join, leave, list)